feat: update and add new core-v3 endpoints
ArkEcosystem/typescript-client pull request #142
Opened 2020-10-28 11:01 UTC by KovacZan

## Summary
Added and updated core-v3 endpoints.
Made it possible to work with dot notation.
Had to adjust parameters like this:
```
"timestamp.from"?: number;
"timestamp.to"?: number;
```
instead of:
```
timestamp?: {
    from?: number;
    to?: number;
}
```
because GET method doesn't parse the object to dot notation.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2020-10-29 03:51 UTC, faustbrian commented on src/resources/blockchain.ts
> +	 * Used to get the latest block and supply of the blockchain.
Remove

2020-10-29 03:51 UTC, faustbrian commented on src/resources/blockchain.ts
> + * Retrieve Blockchain State
Remove

2020-10-29 03:52 UTC, faustbrian requested changes
The input shouldn't change, it should simply be transformed to dot-notation before being sent to the API.

2020-10-30 11:50 UTC, faustbrian requested changes
Use https://github.com/sindresorhus/dot-prop instead of the current implementation.

2020-10-30 11:52 UTC, faustbrian commented
Closing this PR because it contains a large amount of unrelated changes. Feel free to reopen smaller PRs that are submitting specific changes.

2020-10-30 11:52 UTC, closed without merging

2020-10-30 12:20 UTC, KovacZan commented
Could you open a specific branch for core-v3 changes.